// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uloyiazdqsnoftkmkllc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsb3lpYXpkcXNub2Z0a21rbGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzkwNTEsImV4cCI6MjA2Njc1NTA1MX0.X2G37sjj8tDpdsvCWs-xf6BLyn3FR-dYSfkBhnMDcDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);