// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faemngyjtqtevnmsdfjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZW1uZ3lqdHF0ZXZubXNkZmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjkyNjEsImV4cCI6MjA2NzcwNTI2MX0.j0Vm2PoD612dqE1MviUOdvHfJV8_LgWXHNOVpJ19hxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});